Repository kubevirt/application-aware-quota, pull requests merged in 2024-05, with the labels that each got.

#59 Revert .spec.nodeName handling and add a default namespace selector
  pkg/aaq-operator/resources/cluster/aaqserver.go
  pkg/aaq-operator/resources/crds_generated.go
  pkg/aaq-server/handler/handler.go
  pkg/aaq-server/handler/handler_test.go
  pkg/util/patch/patch.go
  staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/types.go
  tests/aaq_operator_test.go
  tests/e2e_application_aware_resource_quota_test.go
  tests/tests_suite_test.go
Labels: dco-signoff: yes, release-note, approved, size/XL, lgtm

#63 BUGFIX: Do not release pods in terminating namespaces.
  pkg/aaq-controller/aaq-gate-controller/aaq-gate-controller.go
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#62 Add requirement for release tool for safe publishing
  hack/release.sh
Labels: size/M, dco-signoff: yes, approved, lgtm, release-note-none

#68 Change default label name to enable-gating
  pkg/aaq-operator/resources/cluster/aaqserver.go
  pkg/aaq-operator/resources/crds_generated.go
  staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/types.go
Labels: dco-signoff: yes, release-note, size/XS, approved, lgtm

#73 Remove leader election test
  tests/aaq-controller-leader-election_test.go
Labels: size/M, dco-signoff: yes, approved, lgtm, release-note-none
