Repository kubevirt/application-aware-quota, pull requests merged in 2024-04, with the labels that each got.

#32 add the Gate Controller as observer to the namespace-quota mapping
  pkg/aaq-controller/aaq-gate-controller/aaq-gate-controller.go
  pkg/aaq-controller/application.go
  tests/e2e_application_aware_cluster_resource_quota.go
  tests/e2e_application_aware_resource_quota_test.go
  tests/e2e_mirrors_quotas_test.go
  tests/utils/aaq-utils.go
  tests/utils/acrq-utils.go
  tests/utils/namespace-utils.go
  tests/utils/pod.go
Labels: dco-signoff: yes, approved, size/XL, lgtm, release-note-none

#39 ARQ-Controller,RQ-Controller: Bugfix arq should be enqueued when arq.spec.scope/arq.status.hard are modifed
  pkg/aaq-controller/arq-controller/arq-controller.go
  pkg/aaq-controller/rq-controller/rq-controller.go
Labels: dco-signoff: yes, approved, size/S, lgtm, release-note-none

#35 Update counting for virtual machines
  go.mod
  go.sum
  pkg/aaq-controller/built-in-usage-calculators/built_in_usage_calculators_suite_test.go
  pkg/aaq-controller/built-in-usage-calculators/virt-launcher-usage-calc.go
  pkg/aaq-controller/built-in-usage-calculators/virt-launcher-usage-calc_test.go
  vendor/github.com/pborman/uuid/.travis.yml
  vendor/github.com/pborman/uuid/CONTRIBUTING.md
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/README.md
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/marshal.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/sql.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
  vendor/kubevirt.io/api/core/v1/deepcopy_generated.go
  vendor/kubevirt.io/api/core/v1/defaults.go
  vendor/kubevirt.io/api/core/v1/schema.go
  vendor/kubevirt.io/api/core/v1/schema_swagger_generated.go
  vendor/kubevirt.io/api/core/v1/types.go
  vendor/kubevirt.io/api/core/v1/types_swagger_generated.go
  vendor/kubevirt.io/api/core/v1/zz_generated.defaults.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, approved, lgtm, release-note-none

#45 Update builder image to include make gen-proto dependencies
  hack/build/config.sh
Labels: dco-signoff: yes, size/XS, release-note-none

#50 CVE-2023-45288: Bump golang.org/x/net to v0.23.0
  go.mod
  go.sum
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, approved, lgtm, release-note-none

#47 Add a wildcard NoSchedule toleration for pods with .spec.nodeName set
  pkg/aaq-server/handler/handler.go
  pkg/aaq-server/handler/handler_test.go
  tests/e2e_application_aware_resource_quota_test.go
Labels: dco-signoff: yes, release-note, approved, lgtm, size/L

#56 adjust libsidecar API to convention
  hack/gen-proto.sh
  pkg/util/net/generated/evaluate.pb.go
  staging/src/kubevirt.io/application-aware-quota-api/libsidecar/evaluator-server-com/evaluate.pb.go
  staging/src/kubevirt.io/application-aware-quota-api/libsidecar/sidecar.go
Labels: dco-signoff: yes, release-note, approved, lgtm, size/L
