Repository kubevirt/application-aware-quota, pull requests merged in 2025-05, with the labels that each got.

#139 types: add ARQ additional printer columns to reflect native RQ behavior
  pkg/aaq-operator/resources/crds_generated.go
  staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/types.go
Labels: dco-signoff: yes, release-note, approved, size/S, lgtm

#142 Revert "types: add ARQ additional printer columns to reflect native RQ behavior"
  pkg/aaq-operator/resources/crds_generated.go
  staging/src/kubevirt.io/application-aware-quota-api/pkg/apis/core/v1alpha1/types.go
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/S

#135 Builder: Improve build process for builder image
  Makefile
  hack/build/bazel-build-builder.sh
  hack/build/builder/Dockerfile
  hack/build/builder/build.sh
  hack/build/builder/common.sh
  hack/build/builder/entrypoint-bazel.sh
  hack/build/builder/entrypoint.sh
  hack/build/builder/publish.sh
  hack/build/builder/rsyncd.conf
  hack/build/common.sh
  hack/build/docker/builder/output-bazel-arch.sh
Labels: dco-signoff: yes, approved, lgtm, size/L, release-note-none

#143 builder: Enable builder image builds for s390x
  hack/build/builder/common.sh
  hack/build/config.sh
Labels: dco-signoff: yes, size/XS, approved, lgtm, release-note-none

#144 builder: Add missing copyright header to entrypoint-bazel.sh
  hack/build/builder/entrypoint-bazel.sh
Labels: dco-signoff: yes, approved, size/S, lgtm, release-note-none

#145 Revert multiarch builder image
  Makefile
  hack/build/bazel-build-builder.sh
  hack/build/builder/build.sh
  hack/build/builder/common.sh
  hack/build/builder/publish.sh
  hack/build/common.sh
  hack/build/docker/builder/Dockerfile
  hack/build/docker/builder/entrypoint-bazel.sh
  hack/build/docker/builder/entrypoint.sh
  hack/build/docker/builder/output-bazel-arch.sh
  hack/build/docker/builder/rsyncd.conf
Labels: dco-signoff: yes, approved, lgtm, size/L, release-note-none
